---
title: "Survival Analysis"
author: Odalys Barrientos
output: html_notebook
---

```{r}
library(survival)
library(broom)
library(readxl)
library(mosaic)
library(reshape2)
library(readxl)


#salinitydata_survive$treament[which(salinitydata_survive$treament == 5 )] <- "05"
survivefit<-survfit(Surv(Time,Status)~ Treatment, data= SalinityData)

summary(survivefit)
print(survivefit)


plot(survivefit, xlab="Survival Time", ylab="Survival Prob", ylim=c(0,1), col = c("black", "red", "blue", "green"))
legend(10, 0.9, legend=c("Treatment 0", "Treatment 5","Treatment 10", "Treatment 15"),
       col=c("black", "red", "blue", "green"), lty=1, cex=0.8)



pairwise_survdiff(Surv(Time,Status)~Treatment,data=SalinityData, p.adjust.method = "bonferroni")
```


```{r}
survivefit<-survfit(Surv(Time,Status)~ Species, data= SalinityData)

summary(survivefit)
print(survivefit)


plot(survivefit, xlab="Survival Time", ylab="Survival Prob", ylim=c(0,1), col = c("black", "red", "blue", "green", "yellow", "orange", "pink", "purple"))
legend(10, 0.9, legend=c("AR", "JV","LS", "NS", "PR", "PS", "QF", "QP"),col = c("black", "red", "blue", "green", "yellow", "orange", "pink", "purple"), lty=1, cex=0.8)


levels(SalinityData$Species)
pairwise_survdiff(Surv(Time,Status)~Species,data=SalinityData, p.adjust.method = "bonferroni")
```

```{r}
freqdata <- FrequencyData
freqdata$status <-1
freqdata$status[is.na(freqdata$Mortality_Julian_day)]<- 0
freqdata$Mortality_Julian_day[is.na(freqdata$Mortality_Julian_day)]<- 274
freqdata$time <- freqdata$Mortality_Julian_day - 91

```

```{r}
survivefit1<-survfit(Surv(time,status)~ Treatment, data= freqdata)
 
summary(survivefit1)
print(survivefit1)
 
 
plot(survivefit1, xlab="Survival Time", ylab="Survival Prob", ylim=c(0,1), col = c("blue", "dark green", "purple"))
legend(10, 0.9, legend=c("Treatment 19", "Treatment 30","Treatment 45"),col=c("blue", "dark green", "purple"), lty=1, cex=0.8)
```

```{r}
library(survminer)
pairwise_survdiff(Surv(time,status)~Treatment,data=freqdata, p.adjust.method = "bonferroni")
```


```{r}
survivefit<-survfit(Surv(time,status)~ Species, data= freqdata)

summary(survivefit)
print(survivefit)


plot(survivefit, xlab="Survival Time", ylab="Survival Prob", ylim=c(0,1), col = c("black", "red", "blue", "green", "yellow", "orange", "pink", "purple"))
legend(10, 0.9, legend=c("AR", "JV","LS", "NS", "PR", "PS", "QF", "QP"),col = c("black", "red", "blue", "green", "yellow", "orange", "pink", "purple"), lty=1, cex=0.8)



pairwise_survdiff(Surv(time,status)~Species,data=freqdata, p.adjust.method = "bonferroni")
```



