---
title: "Daneshgar: Data Cleaning and Descriptives"
author: Odalys Barrientos
output: html_notebook
---
# Importing & Creating New Data Sets
```{r, message=FALSE}
library(readxl)
library(mosaic)
library(writexl)
library(ggplot2)
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)
library("RColorBrewer")

# Importing Data
# salinity.data <- read_excel("GreenhouseDataFINAL.xlsx", sheet = "Salinity Data")
# freq.data <- read_excel("GreenhouseDataFINAL.xlsx", sheet = "Flood Frequency Data")
# salinity.biomass <- read_excel("GreenhouseDataFINAL.xlsx", sheet = "Salinity biomass")
# freq.biomass <- read_excel("GreenhouseDataFINAL.xlsx", sheet = "Frequency Biomass")

# Creating New Data sets
# survival.salt <- data.frame(Species = salinity.data$Species, Treatment = salinity.data$Treatment, Rep = salinity.data$Rep, Julian.Day.Mortality = salinity.data$`Julian day mortality`, salinity.data[,9:21] )
# survival.freq <- data.frame(Species = freq.data$Species, Treatment = freq.data$Treatment, Rep = freq.data$Rep, Julian.Day.Mortality = freq.data$`Julian day mortality`, freq.data[,9:21] )

# Renaming time columns
# names(survival.salt)[5:17] <- c("Time1","Time2","Time3","Time4","Time5","Time6","Time7","Time8","Time9","Time10","Time11","Time12", "Time13")
# 
# names(survival.freq)[5:17] <- c("Time1","Time2","Time3","Time4","Time5","Time6","Time7","Time8","Time9","Time10","Time11","Time12", "Time13")

# Exporting New Data sets
#write_xlsx(survival.salt,"SurvivalSALTdata.xlsx")
#write_xlsx(survival.freq,"SurvivalFREQdata.xlsx")
```

# Importing Data 
```{r}
SalinityData <- read_excel("Salinitydata.xlsx")
# Removing columns we do NOT need
SalinityData <- SalinityData[,c(1:8, 23:25,33)]

FrequencyData <- read_excel("Flood_Frequency .xlsx")
FrequencyData <- FrequencyData[,c(1:8, 23:25,29)]


SalinityData$Treatment <- as.factor(SalinityData$Treatment)
SalinityData$Species <- as.factor(SalinityData$Species)

FrequencyData$Treatment <- as.factor(FrequencyData$Treatment)
FrequencyData$Species <- as.factor(FrequencyData$Species)
```

# favstats SALINITY
```{r}
favstats(SalinityData$total.grams)

favstats(total.grams~Species, data = SalinityData)

favstats(total.grams~Treatment, data = SalinityData)

favstats(total.grams~Species|Treatment, data = SalinityData)
```

# favstats FREQUENCY
```{r}
favstats(FrequencyData$Total.g)

favstats(Total.g~Species, data = FrequencyData)

favstats(Total.g~Treatment, data = FrequencyData)

favstats(Total.g~Species|Treatment, data = FrequencyData)
```

# Creating Volume variable (SALINITY & FREQUENCY)
```{r}
# Creating Volume variable
SalinityData$Final.Height.mm <- SalinityData$Final.Height.cm*10
SalinityData$Final.Vol.mm <- pi*((SalinityData$Final.Diam.mm)/2)^2*SalinityData$Final.Height.mm
SalinityData$Initial.Height.mm <- SalinityData$Initial.Height.cm*10

FrequencyData$Final.Height.mm <- FrequencyData$F_Height_cm*10
FrequencyData$Final.Vol.mm <- pi*((FrequencyData$F_Diameter_mm)/2)^2*FrequencyData$Final.Height.mm
FrequencyData$Initial.Height.mm <- FrequencyData$I_Height_cm*10

# Removing Height in Inches columns
SalinityData <- SalinityData[,c(1:4, 6, 8:14)]
FrequencyData <- FrequencyData[, c(1:4, 6, 8:14)]


# When we were going to make models to predict initial biomass
plot(SalinityData$Final.Vol.mm, SalinityData$total.grams)
```


# Density & Box Plots SALINITY
```{r}
Density.species <- ggplot(data=SalinityData, aes(x=total.grams, group=Species, fill=Species)) +
    geom_density(adjust=1.5, alpha=.4) +xlim(-100, 1300)+
    theme_ipsum()+ xlab("Total Biomass (grams)")
Density.species

Desnity.treatment <- ggplot(data=SalinityData, aes(x=total.grams, group=Treatment, fill=Treatment)) +
    geom_density(adjust=1.5, alpha=.4) + xlim(-500, 1000)+
    theme_ipsum()+ xlab("Total Biomass (grams)")
Desnity.treatment



ggplot(SalinityData, aes(x=total.grams, y=Species, fill=Species)) +
  geom_boxplot()+ xlab("Total Biomass (grams)")

ggplot(SalinityData, aes(x=total.grams, y=Treatment, fill=Treatment)) +
  geom_boxplot(position=position_dodge(1)) + xlab("Total Biomass (grams)")
```

# Density & Box plots FREQUENCY 
```{r}
Density.species <- ggplot(data=FrequencyData, aes(x=Total.g, group=Species, fill=Species)) +
    geom_density(adjust=1.5, alpha=.4) +xlim(-50, 500)+
    theme_ipsum() + xlab("Total Biomass (grams)")
Density.species

Desnity.treatment <- ggplot(data=FrequencyData, aes(x=Total.g, group=Treatment, fill=Treatment)) +
    geom_density(adjust=1.5, alpha=.4) + xlim(-500, 1300)+
    theme_ipsum() + xlab("Total Biomass (grams)")
Desnity.treatment



ggplot(FrequencyData, aes(x=Total.g, y=Species, fill=Species)) +
  geom_boxplot()+ xlab("Total Biomass (grams)")

ggplot(FrequencyData, aes(x=Total.g, y=Treatment, fill=Treatment)) +
  geom_boxplot(position=position_dodge(1)) + xlab("Total Biomass (grams)")
```

# QQ PLOTS SALINITY & FREQUENCY
```{r}
# SALINITY
gf_qq(~total.grams|Treatment, data=SalinityData) %>% gf_qqline()

gf_qq(~total.grams|Species, data=SalinityData) %>% gf_qqline()

# FREQUENCY
gf_qq(~total.grams|Treatment, data=SalinityData) %>% gf_qqline()

gf_qq(~total.grams|Species, data=SalinityData) %>% gf_qqline()
```
# Interaction Pots SALINITY & FREQUENCY
```{r}
# SALINITY
interaction.plot(x.factor = SalinityData$Treatment, trace.factor = SalinityData$Species, response = SalinityData$total.grams,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Total Biomass (grams)", xlab = "Species", lty = 1, lwd = 2, trace.label = "Salinity Level")

#######################################################
percent.change.diameter <- (SalinityData$Final.Diam.mm - SalinityData$Initial.Diam.mm)/SalinityData$Initial.Diam.mm
SalinityData$percent.change.diameter <- percent.change.diameter*100

interaction.plot(x.factor = SalinityData$Treatment, trace.factor = SalinityData$Species, response = SalinityData$percent.change.diameter,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Percent Change in Diameter", xlab = "Salinity Level", lty = 1, lwd = 2, trace.label = "Species")

#######################################################
percent.change.height <- (SalinityData$Final.Height.cm- SalinityData$Initial.Height.cm)/SalinityData$Initial.Height.cm
SalinityData$percent.change.height <- percent.change.height*100

interaction.plot(x.factor = SalinityData$Treatment, trace.factor = SalinityData$Species, response = SalinityData$percent.change.height,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Percent Change in Height", xlab = "Salinity Level", lty = 1, lwd = 2, trace.label = "Species")


# FREQUENCY
interaction.plot(x.factor = FrequencyData$Treatment, trace.factor = FrequencyData$Species, response = FrequencyData$Total.g,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Total Biomass (grams)", xlab = "Species", lty = 1, lwd = 2, trace.label = "Level of Frequency")

#######################################################
percent.change.diameter <- (FrequencyData$F_Diameter_mm - FrequencyData$I_Diameter_mm)/FrequencyData$I_Diameter_mm
FrequencyData$percent.change.diameter <- percent.change.diameter*100

interaction.plot(x.factor = FrequencyData$Treatment, trace.factor = FrequencyData$Species, response = FrequencyData$percent.change.diameter,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Percent Change in Diameter", xlab = "Level of Frequency", lty = 1, lwd = 2, trace.label = "Species")

#######################################################
percent.change.height <- (FrequencyData$F_Height_cm - FrequencyData$I_Height_cm)/FrequencyData$I_Height_cm
FrequencyData$percent.change.height <- percent.change.height*100

interaction.plot(x.factor = FrequencyData$Treatment, trace.factor = FrequencyData$Species, response = FrequencyData$percent.change.height,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Percent Change in Height", xlab = "Level of Frequency", lty = 1, lwd = 2, trace.label = "Species")

```



# Anovas SALINITY
```{r}
# standardized???????

SalinityData$Standard.biomass <- (SalinityData$total.grams - mean(SalinityData$total.grams))/sd(SalinityData$total.grams)
SalinityData$Standard.vol.change <- (SalinityData$change.in.vol - mean(SalinityData$change.in.vol))/sd(SalinityData$change.in.vol)

anova.standard <- aov(Standard.biomass~Treatment + Species + Treatment*Species, data = SalinityData)
Anova(anova.standard, type="III")

anova.standard.vol <- aov(Standard.vol.change~Treatment + Species + Treatment*Species, data = SalinityData)
Anova(anova.standard.vol, type="III")

interaction.plot(x.factor = SalinityData$Treatment, trace.factor = SalinityData$Species, response = SalinityData$Standard.biomass,  col = brewer.pal(n = 8, name = "Set2"), fun = median, ylab = "Total Biomass (grams)", xlab = "Species", lty = 1, lwd = 2, trace.label = "Salinity Level")

```


```{r}
library(car)

# by treatment
simple.trtmt <- aov(total.grams~Treatment, data = SalinityData)
Anova(simple.trtmt, type="III")

# by species
simple.species <- aov(total.grams~Species, data = SalinityData)
Anova(simple.species, type="III")

# by treatment and species
simple.anova <- aov(total.grams~Treatment + Species, data = SalinityData)
Anova(simple.anova, type="III")

# by treatment and species and interaction???
simple.anova.int <- aov(total.grams~Treatment + Species + Treatment*Species, data = SalinityData)
Anova(simple.anova.int, type="III")
# Pval for interaction = 0.069 
# This is good. We want all species to be influenced by salinity the same way. Hopefull as salinity goes up bio mass decreases.
```


```{r}
SalinityData$Initial.Vol.mm <- pi*((SalinityData$Initial.Diam.mm)/2)^2*SalinityData$Initial.Height.mm

# Response: Volume
anova.vol.I <- aov(Initial.Vol.mm~Treatment+Species, data = SalinityData)
Anova(anova.vol.I, type="III")
anova.vol.F <- aov(Final.Vol.mm~Treatment+Species + Treatment*Species, data = SalinityData)
Anova(anova.vol.F, type="III")

# change in volume 
SalinityData$change.in.vol <- SalinityData$Final.Vol.mm - SalinityData$Initial.Vol.mm
anova.vol.change <- aov(change.in.vol~Treatment+Species + Treatment*Species, data = SalinityData)
Anova(anova.vol.change, type="III")

# Response: Height
anova.H.I <- aov(Initial.Height.mm~Treatment+Species, data = SalinityData)
Anova(anova.H.I, type="III")
anova.H.F <- aov(Final.Height.mm~Treatment+Species + Treatment*Species, data = SalinityData)
Anova(anova.H.F, type="III")

# Response: Diameter
anova.D.I <- aov(Initial.Diam.mm~Treatment+Species, data = SalinityData)
Anova(anova.D.I, type="III")
anova.D.F <- aov(Final.Diam.mm~Treatment+Species + Treatment*Species, data = SalinityData)
Anova(anova.D.F, type="III")
```


# Anovas FREQUENCY
```{r}
# by treatment
F.trtmt <- aov(Total.g~Treatment, data = FrequencyData)
Anova(F.trtmt, type="III")

# by species
F.species <- aov(Total.g~Species, data = FrequencyData)
Anova(F.species, type="III")

# by treatment and species
F.anova <- aov(Total.g~Treatment + Species, data = FrequencyData)
Anova(F.anova, type="III")

# by treatment and species and interaction???
F.anova.int <- aov(Total.g~Treatment + Species + Treatment*Species, data = FrequencyData)
Anova(F.anova.int, type="III")

# Pval for interaction = 0.04
```

```{r}
FrequencyData$Initial.Vol.mm <- pi*((FrequencyData$I_Diameter_mm)/2)^2*FrequencyData$Initial.Height.mm

# Response: Volume
anova.vol.I <- aov(Initial.Vol.mm~Treatment+Species, data = FrequencyData)
Anova(anova.vol.I, type="III")
anova.vol.F <- aov(Final.Vol.mm~Treatment+Species + Treatment*Species, data = FrequencyData)
Anova(anova.vol.F, type="III")

# Response: Height
anova.H.I <- aov(Initial.Height.mm~Treatment+Species, data = FrequencyData)
Anova(anova.H.I, type="III")
anova.H.F <- aov(Final.Height.mm~Treatment+Species + Treatment*Species, data = FrequencyData)
Anova(anova.H.F, type="III")

# Response: Diameter
anova.D.I <- aov(I_Diameter_mm~Treatment+Species, data = FrequencyData)
Anova(anova.D.I, type="III")
anova.D.F <- aov(F_Diameter_mm~Treatment+Species + Treatment*Species, data = FrequencyData)
Anova(anova.D.F, type="III")
``` 


```{r}
library(lme4)
library(nlme)


mixed.anova <- lmer(total.grams ~ Treatment + (1|Species), data = SalinityData)
mixed.anova
summary(mixed.anova)
Anova(mixed.anova, type = "III")


```

```{r}
SalinityData$Status <- 1 # dead
SalinityData$Status[is.na(SalinityData$Julian.day.mortality)] <- 0 # alive

SalinityData <- SalinityData[, c(1:3,5,14)]

SalinityData$Julian.day.mortality[is.na(SalinityData$Julian.day.mortality)] <-274 


SalinityData$Time <- SalinityData$Julian.day.mortality - 91
# SalinityData$Julian.day.mortality[is.na(SalinityData$Julian.day.mortality)] <- 274


tally(SalinityData$Treatment~SalinityData$Status)

```

